CREATE TABLE users (
    id integer primary key generated by default as identity,
    username text unique not null,
    password text not null,
    admin boolean not null default false,
    created_at TIMESTAMPTZ default now() not null
);