create table pomodoro_sessions (
    id integer primary key generated by default as identity,
    session_name text not null,
    session_description text,
    session_end TIMESTAMPTZ default now() not null,
    session_owner integer references users(id) on delete cascade not null
);